### PR TITLE
Start to prepare for 2018-03-16.

### PR DESCRIPTION
**Pull request by poweihuang17**
- [ ] Embedded World 2018 [link1](https://www.codasip.com/2018/03/13/notes-from-ew2018/) [Link2](http://www.eenewseurope.com/news/interview-rick-oconnor-risc-v-foundation/page/0/1) @xfguo
- [x] [The European Processor Initiative (EPI) to develop the processor that will be at the heart of the European exascale supercomputer effort](http://primeurmagazine.com/weekly/AE-PR-03-18-87.html) @xfguo
- [x] [Heterogeneous Hubbub](https://semiengineering.com/heterogeneous-hubbub/) @xfguo
- [x] [QuickLogic joins RISC-V Foundation](https://www.electronicsweekly.com/news/quicklogic-joins-risc-v-foundation-2018-03/) @xfguo
- [x] 胡振波文章 @xfguo

### CODE REVIEW

**Comment by poweihuang17** [comment]
雄飛，你有加入EPI的消息了嗎？

**Comment by xfguo** [comment]
@poweihuang17 有了

**Comment by poweihuang17** [comment]
https://ghc.haskell.org/trac/ghc/ticket/14903
haskell的這個似乎只是一個bug report，不是一個port。所以我先不報。

**Comment by poweihuang17** [comment]
先這樣，明早起來再加一點。

**Pull request merged**
