### PR TITLE
update home page & fresh freedom* clone images.

### PR DESCRIPTION
**Pull request by xfguo**
- update home page & fresh freedom* clone images
- css: better fonts for code block.

### CODE REVIEW

**Comment by wsong83** [comment]
It looks good to me.

**Comment by wsong83** [comment]
May be we need some content on the README.md of this repo?

**Comment by xfguo** [comment]
@wsong83  I will merge it first. Later let's talk about the README.md

**Comment by xfguo** [comment]
@wsong83  I will merge it first. Later let's talk about the README.md

**Pull request merged**
